
services:
  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  chat-service:
    build: ./chat-service
    ports:
      - "3005:3005"
    depends_on:
      - redis
      - rabbitmq
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    env_file:
      - ./chat-service/.env.docker
 
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file:
      - ./api-gateway/.env.docker

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - rabbitmq
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    env_file:
      - ./auth-service/.env.docker

  friend-service:
    build: ./friend-service
    ports:
      - "3003:3003"
    depends_on:
      - rabbitmq
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    env_file:
      - ./friend-service/.env.docker
  user-service:
    build: ./user-service
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    env_file:
      - ./user-service/.env.docker

  notification-service:
    build: ./notification-service
    ports:
      - "3004:3004"
    depends_on:
      - rabbitmq
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    env_file:
      - ./notification-service/.env.docker


volumes:
  redis-data:
  rabbitmq-data:
